import type { Metadata } from "next";

import { Quicksand } from "next/font/google";

import localFont from "next/font/local";

import Header from "@components/header";

import "@styles/globals.scss";

const quicksand = Quicksand({
  subsets: ["latin"],
});

const rey = localFont({
  src: "../public/fonts/reey.woff2",
  variable: "--font-rey",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} ${rey.variable}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
