import { getPlayerGroups } from "../calc"
import { Player, Round, Entrant, Players } from "../classes"

//All entrant starting (driver/team) data
export const entrantData = {
  drivers: {
    ham: new Entrant("Hamilton", "ham", "mer"),
    bot: new Entrant("Bottas", "bot", "mer"),
    lec: new Entrant("Leclerc", "lec", "fer"),
    sai: new Entrant("Sainz", "sai", "fer"),
    ver: new Entrant("Verstappen", "ver", "rbr"),
    per: new Entrant("Perez", "per", "rbr"),
    alo: new Entrant("Alonso", "alo", "alp"),
    oco: new Entrant("Ocon", "oco", "alp"),
    sch: new Entrant("Schumacher", "sch", "has"),
    maz: new Entrant("Mazepin", "maz", "has"),
    nor: new Entrant("Norris", "nor", "mcl"),
    ric: new Entrant("Ricciardo", "ric", "mcl"),
    vet: new Entrant("Vettel", "vet", "ast"),
    str: new Entrant("Stroll", "str", "ast"),
    rai: new Entrant("Raikkonen", "rai", "alf"),
    gio: new Entrant("Giovinazzi", "gio", "alf"),
    tsu: new Entrant("Tsunoda", "tsu", "alt"),
    gas: new Entrant("Gasly", "gas", "alt"),
    lat: new Entrant("Latifi", "lat", "wil"),
    rus: new Entrant("Russell", "rus", "wil"),
  },
  teams: {
    mer: new Entrant("Mercedes", "mer"),
    fer: new Entrant("Ferrari", "fer"),
    rbr: new Entrant("Red Bull", "rbr"),
    mcl: new Entrant("McLaren", "mcl"),
    alp: new Entrant("Alpine", "alp"),
    alt: new Entrant("Alpha Tauri", "alt"),
    ast: new Entrant("Aston Martin", "ast"),
    has: new Entrant("Haas", "has"),
    alf: new Entrant("Alfa Romeo", "alf"),
    wil: new Entrant("Williams", "wil"),
  },
}
const {
  ham,
  bot,
  lec,
  sai,
  ver,
  per,
  alo,
  oco,
  sch,
  maz,
  nor,
  ric,
  vet,
  str,
  rai,
  gio,
  tsu,
  gas,
  lat,
  rus,
} = entrantData.drivers
const { mer, fer, rbr, mcl, alp, alt, ast, has, alf, wil } = entrantData.teams
export const drivers = entrantData.drivers
export const teams = entrantData.teams

//Player data
export const players: Players = {
  david: new Player(
    "David",
    ["aberystwyth", "brr", "herefordshire"],
    [
      ham,
      bot,
      ver,
      per,
      lec,
      vet,
      sai,
      str,
      ric,
      nor,
      alo,
      gas,
      oco,
      tsu,
      rai,
      gio,
      rus,
      sch,
      lat,
      maz,
    ],
    [mer, rbr, fer, ast, mcl, alp, alt, alf, wil, has]
    //Post pre season testing predictions
    //[ham,ver,bot,per,ric,nor,vet,lec,str,alo,sai,gas,ocon,tsu,rai,gio,rus,sch,lat,maz]
    //[mer, rbr, mcl, ast, fer, alp, alt, alf, wil, has]
  ),
  jack: new Player(
    "Jack",
    ["aberystwyth", "brr"],
    [
      ham,
      ver,
      bot,
      per,
      vet,
      ric,
      lec,
      str,
      sai,
      alo,
      nor,
      oco,
      gas,
      tsu,
      rai,
      gio,
      rus,
      sch,
      maz,
      lat,
    ],
    [mer, rbr, ast, fer, mcl, alp, alt, alf, wil, has]
  ),
  tom: new Player(
    "Tom",
    ["brr", "dyson", "herefordshire"],
    [
      ham,
      ver,
      bot,
      per,
      ric,
      vet,
      nor,
      lec,
      str,
      alo,
      sai,
      oco,
      gas,
      tsu,
      rai,
      gio,
      rus,
      sch,
      maz,
      lat,
    ],
    [mer, rbr, mcl, ast, fer, alp, alt, alf, wil, has]
  ),
  pete: new Player(
    "Pete",
    ["herefordshire"],
    [
      ham,
      per,
      ver,
      bot,
      ric,
      vet,
      nor,
      str,
      alo,
      lec,
      sai,
      gas,
      tsu,
      oco,
      rai,
      gio,
      sch,
      maz,
      rus,
      lat,
    ],
    [rbr, mer, mcl, ast, fer, alp, alt, alf, has, wil]
  ),
  will: new Player(
    "Will",
    ["aberystwyth"],
    [
      ver,
      ham,
      ric,
      per,
      bot,
      vet,
      alo,
      lec,
      nor,
      sai,
      str,
      gas,
      oco,
      tsu,
      rai,
      gio,
      sch,
      rus,
      maz,
      lat,
    ],
    [rbr, mer, mcl, ast, alp, fer, alt, alf, has, wil]
  ),
  annie: new Player(
    "Annie",
    ["dyson"],
    [
      ham,
      ver,
      bot,
      per,
      vet,
      ric,
      lec,
      str,
      nor,
      sai,
      gas,
      oco,
      alo,
      tsu,
      rai,
      rus,
      gio,
      sch,
      maz,
      lat,
    ],
    [mer, rbr, ast, mcl, fer, alp, alt, alf, has, wil]
  ),
  james: new Player(
    "James",
    ["dyson"],
    [
      ham,
      ver,
      bot,
      ric,
      nor,
      per,
      lec,
      str,
      vet,
      sai,
      alo,
      gas,
      oco,
      tsu,
      sch,
      rai,
      maz,
      rus,
      gio,
      lat,
    ],
    [mer, rbr, mcl, ast, fer, alp, alt, has, alf, wil]
  ),
  jacopo: new Player(
    "Jacopo",
    ["dyson"],
    [
      ham,
      bot,
      ver,
      ric,
      per,
      vet,
      lec,
      alo,
      sai,
      str,
      nor,
      gas,
      oco,
      rai,
      gio,
      sch,
      rus,
      tsu,
      maz,
      lat,
    ],
    [mer, rbr, mcl, fer, ast, alp, alt, alf, has, wil]
  ),
  alex: new Player(
    "Alex",
    ["dyson"],
    [
      ham,
      ver,
      bot,
      lec,
      nor,
      ric,
      vet,
      alo,
      sai,
      per,
      str,
      oco,
      gas,
      tsu,
      rai,
      gio,
      rus,
      sch,
      maz,
      lat,
    ],
    [mer, rbr, mcl, fer, ast, alp, alt, alf, wil, has]
  ),
  formula1: new Player(
    //https://www.formula1.com/en/latest/article.f1-power-rankings-weve-ranked-the-teams-from-10-to-1-after-pre-season.6DKunC8CA9nHHu6MkuiIQQ.html
    "formula1.com",
    ["misc"],
    [],
    [rbr, mer, mcl, alp, fer, alt, ast, alf, wil, has]
  ),
  average: new Player("Average", ["misc"], [], []),
  karun: new Player(
    //https://twitter.com/karunchandhok/status/1371374740217159680
    "Karun Sky F1",
    ["misc"],
    [],
    [rbr, mer, alt, mcl, alp, fer, ast, alf, wil, has]
  ),
}
export const playerGroupsArr = getPlayerGroups(players)

//Round data
export let rounds = [
  new Round(
    "Bahrain GP",
    [
      ham,
      ver,
      bot,
      nor,
      per,
      lec,
      ric,
      sai,
      tsu,
      str,
      rai,
      gio,
      oco,
      rus,
      vet,
      sch,
      gas,
      lat,
      alo,
      maz,
    ],
    [mer, rbr, mcl, fer, alt, ast, alf, alp, wil, has]
  ),
  new Round(
    "Imola GP",
    [
      ham,
      ver,
      nor,
      lec,
      bot,
      sai,
      ric,
      per,
      str,
      gas,
      tsu,
      oco,
      alo,
      rai,
      gio,
      rus,
      vet,
      sch,
      maz,
      lat,
    ],
    [mer, rbr, mcl, fer, alt, ast, alp, alf, wil, has]
  ),
  new Round(
    "Portuguese GP",
    [
      ham,
      ver,
      nor,
      bot,
      lec,
      per,
      ric,
      sai,
      oco,
      gas,
      str,
      alo,
      tsu,
      rai,
      gio,
      vet,
      rus,
      sch,
      maz,
      lat,
    ],
    [mer, rbr, mcl, fer, alp, alt, ast, alf, wil, has]
  ),
  new Round(
    "Spanish GP",
    [
      ham,
      ver,
      bot,
      nor,
      lec,
      per,
      ric,
      sai,
      oco,
      gas,
      str,
      alo,
      tsu,
      rai,
      gio,
      vet,
      rus,
      sch,
      lat,
      maz,
    ],
    [mer, rbr, mcl, fer, alp, alt, ast, alf, wil, has]
  ),
  new Round(
    "Monaco GP",
    [
      ver,
      ham,
      nor,
      bot,
      per,
      lec,
      sai,
      ric,
      gas,
      oco,
      vet,
      str,
      alo,
      tsu,
      gio,
      rai,
      rus,
      lat,
      sch,
      maz,
    ],
    [rbr, mer, mcl, fer, ast, alt, alp, alf, wil, has]
  ),
  new Round(
    "Azerbaijan GP",
    [
      ver,
      ham,
      per,
      nor,
      lec,
      bot,
      sai,
      gas,
      vet,
      ric,
      alo,
      oco,
      str,
      tsu,
      rai,
      gio,
      sch,
      rus,
      maz,
      lat,
    ],
    [rbr, mer, fer, mcl, alt, ast, alp, alf, has, wil]
  ),
  new Round(
    "French GP",
    [
      ver,
      ham,
      per,
      nor,
      bot,
      lec,
      sai,
      gas,
      ric,
      vet,
      alo,
      oco,
      str,
      tsu,
      rai,
      gio,
      rus,
      sch,
      maz,
      lat,
    ],
    [rbr, mer, mcl, fer, alt, ast, alp, alf, wil, has]
  ),
  new Round(
    "Styrian GP",
    [
      ver,
      ham,
      per,
      nor,
      bot,
      lec,
      sai,
      gas,
      ric,
      vet,
      alo,
      str,
      oco,
      tsu,
      rai,
      gio,
      rus,
      sch,
      maz,
      lat,
    ],
    [rbr, mer, mcl, fer, alt, ast, alp, alf, wil, has]
  ),
  new Round(
    "Austrian GP",
    [
      ver,
      ham,
      per,
      nor,
      bot,
      lec,
      sai,
      ric,
      gas,
      vet,
      alo,
      str,
      oco,
      tsu,
      rai,
      gio,
      rus,
      sch,
      maz,
      lat,
    ],
    [rbr, mer, mcl, fer, alt, ast, alp, alf, wil, has]
  ),
  new Round(
    "British GP",
    [
      ver,
      ham,
      nor,
      bot,
      per,
      lec,
      sai,
      ric,
      gas,
      vet,
      alo,
      str,
      oco,
      tsu,
      rai,
      gio,
      rus,
      sch,
      maz,
      lat,
    ],
    [rbr, mer, mcl, fer, alt, ast, alp, alf, has, wil]
  ),
  new Round(
    "Hungarian GP",
    [
      ham,
      ver,
      nor,
      bot,
      per,
      lec,
      sai,
      ric,
      vet,
      gas,
      oco,
      alo,
      str,
      tsu,
      lat,
      rus,
      rai,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, mcl, fer, alp, ast, alt, wil, alf, has]
  ),
  new Round(
    "Belgium GP",
    [
      ham,
      ver,
      nor,
      bot,
      per,
      sai,
      lec,
      ric,
      gas,
      oco,
      alo,
      vet,
      tsu,
      str,
      rus,
      lat,
      rai,
      gio,
      sch,
      maz,
    ],
    [rbr, mer, mcl, fer, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "Dutch GP",
    [
      ver,
      ham,
      bot,
      nor,
      per,
      lec,
      sai,
      gas,
      ric,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      lat,
      rai,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, fer, mcl, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "Italian GP",
    [
      ver,
      ham,
      bot,
      nor,
      per,
      lec,
      sai,
      ric,
      gas,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      lat,
      rai,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, mcl, fer, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "Russian GP",
    [
      ham,
      ver,
      bot,
      nor,
      per,
      sai,
      lec,
      ric,
      gas,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      lat,
      rai,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, mcl, fer, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "Turkish GP",
    [
      ver,
      ham,
      bot,
      nor,
      per,
      sai,
      lec,
      ric,
      gas,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      lat,
      rai,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, mcl, fer, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "American GP",
    [
      ver,
      ham,
      bot,
      per,
      nor,
      lec,
      sai,
      ric,
      gas,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      lat,
      rai,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, mcl, fer, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "Mexico GP",
    [
      ver,
      ham,
      bot,
      per,
      nor,
      lec,
      sai,
      ric,
      gas,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      rai,
      lat,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, fer, mcl, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "Brazilian GP",
    [
      ver,
      ham,
      bot,
      per,
      nor,
      lec,
      sai,
      ric,
      gas,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      rai,
      lat,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, fer, mcl, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "Qatarian GP",
    [
      ver,
      ham,
      bot,
      per,
      nor,
      lec,
      sai,
      ric,
      gas,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      rai,
      lat,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, fer, mcl, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "Saudi Arabian GP",
    [
      ver,
      ham,
      bot,
      per,
      lec,
      nor,
      sai,
      ric,
      gas,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      rai,
      lat,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, fer, mcl, alp, alt, ast, wil, alf, has]
  ),
  new Round(
    "Abu Dhabi GP",
    [
      ver,
      ham,
      bot,
      per,
      sai,
      nor,
      lec,
      ric,
      gas,
      alo,
      oco,
      vet,
      str,
      tsu,
      rus,
      rai,
      lat,
      gio,
      sch,
      maz,
    ],
    [mer, rbr, fer, mcl, alp, alt, ast, wil, alf, has]
  ),
]
